### ISSUE TITLE
Security - Mozilla Observatory

### ISSUE THREAD

**Issue by bpabiszczak** [joforce/JoForceCRM#3]
![image](https://user-images.githubusercontent.com/10197525/29203534-e719bfe8-7e71-11e7-9401-7cf2070b7001.png)

**Comment by fenzik** [comment]
Thanks for reporting @bpabiszczak 

We fixed it.

**Comment by bpabiszczak** [comment]
Why haven’t the changes been uploaded to GitHub? I don’t think you fixed the problems on the server layer, this approach causes every person who downloads your system to still experience these problems. The solution should be hard coded directly in the system code.

**Comment by fenzik** [comment]
No code changes.

Changed the demo domain from http to https.

**Comment by bpabiszczak** [comment]
![image](https://user-images.githubusercontent.com/10197525/29453048-9c902178-8408-11e7-8b84-2a01419b9c0d.png)

**Comment by bpabiszczak** [comment]
![image](https://user-images.githubusercontent.com/10197525/29453073-aa58e146-8408-11e7-9c48-c720c98f9baa.png)

**Comment by fenzik** [comment]
> Content Security Policy |   | -25 | Content Security Policy (CSP) header not implemented |  

**- Not fixed**

> Cookies |   | -40 | Session cookie set without using the Secure flag or set over http |  

**- To be handled in the apache conf - _Ref: https://geekflare.com/httponly-secure-cookie-apache/_**

> HTTP Strict Transport Security |   | -20 | HTTP Strict Transport Security (HSTS) header not implemented |  
> X-Content-Type-Options |   | -5 | X-Content-Type-Options header not implemented |  
> X-Frame-Options |   | -20 | X-Frame-Options (XFO) header not implemented |  
> X-XSS-Protection |   | -10 | X-XSS-Protection header not implemented

**- Enable HSTS & SSL Strict in apache SSL**

**Comment by fenzik** [comment]
Thank you for the feedbacks, reopening the thread for further discussions.

**Comment by fenzik** [comment]
I'm getting the same for the root domain https://observatory.mozilla.org/analyze.html?host=yetiforce.com

**Comment by bpabiszczak** [comment]
These security measures should be hard coded in the application, instead of being configured on the server each time. It results from the fact that better to add a safeguard in the app than force your users to configure their servers countless times, especially that some users just can’t do that.

Following this logic you could as well set all folder permissions to 777 because users can change the permissions themselves, or give public access to the backup copy folder because if the user creates a backup then he should also change the permissions. This approach is dangerous and not recommended!

The YetiForce website is based on Joomla, and Joomla doesn’t secure the headers configuration properly! It doesn’t mean that your system shouldn’t do that. We are talking about joForce/ YetiForce and not about Joomla.

Since you became a CRM software producer you should focus on ensuring proper security, nobody will do that for you. Unless you decide to ignore it like SuiteCRM, coreBOS, or Vtiger do.

**Comment by fenzik** [comment]
@bpabiszczak Committed the changes.
